In [ ]:
# 라이브러리 임포트
import os
import pandas as pd
import chardet

In [ ]:
# 기본경로 설정
path_dateset = 'G:/내 드라이브/DataSet/'

In [ ]:
# 확장자 가져오기 (Ex) .csv, .xlsx
def Extract_Extension(file_path):
    _, file_extension = os.path.splitext(file_path)
    return file_extension

In [ ]:
# 파일명 가져오기
def Extract_Filename(file_path):
    file_name = os.path.basename(file_path)
    filename_without_extension, _ = os.path.splitext(file_name)
    return filename_without_extension

In [ ]:
# 파일의 Encoding을 확인
def Get_ExcelEncoding(file_path):
    with open(file_path, 'rb') as f:
        result = chardet.detect(f.read(10000))

    encoding = result['encoding']
    return encoding

In [ ]:
import time

In [ ]:
# chunk_size : 나눠서 읽어올 크기 (기본값 : 100만개)
def Read_Chunk(file_path, chunk_size = 10**6):
    try:
        _encoding = Get_ExcelEncoding(file_path)
        result_df = pd.DataFrame()

        for i, chunk in enumerate(pd.read_csv(file_path, chunksize=chunksize, encoding=_encoding, low_memory=False)):
            # 청크 데이터프레임을 가공합니다. 여기서는 예시로 첫 5개 행만 가져옵니다.
            # processed_chunk = chunk.head()
            processed_chunk = chunk

            # 결과 데이터프레임에 청크를 추가합니다.
            result_df = pd.concat([result_df, processed_chunk])
            print(f" Processed a chunk of size: {len(chunk)}")

        return result_df
    except Exception as e:
        print(f"An error occurred while processing the file: {e}")

In [ ]:
def Read_pyarrow(file_path):
    from pyarrow import csv

    pyarrow_df = csv.read_csv(file_path).to_pandas()

    return pyarrow_df

In [ ]:
def Read_dask(file_path, _dtype):
    import dask.dataframe as dd

    _encoding = Get_ExcelEncoding(file_path)
    dask_df = dd.read_csv(file_path, encoding=_encoding, dtype = _dtype)

    return dask_df

In [ ]:
# chunk_size : 나눠서 읽어올 크기 (기본값 : 100만개)
def Read_nrows(file_path, _nrows = 10):
    try:
        _encoding = Get_ExcelEncoding(file_path)
        result_df = pd.DataFrame()

        result_df = pd.read_csv(file_path, nrows= _nrows, encoding=_encoding, low_memory=False)

        return result_df
    except Exception as e:
        print(f"An error occurred while processing the file: {e}")

In [ ]:
file_path = 'G:/내 드라이브/DataSet/_최종 병합 파일/서울특별시 공공자전거 대여소별 이용정보(시간대별)/서울특별시 공공자전거 대여소별 이용정보(시간대별)_2020.csv'

In [1]:
Read_nrows(file_path, 5).columns

NameError: name 'Read_nrows' is not defined

In [ ]:
df_rtn.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [ ]:
Get_ExcelEncoding(file_path)

'utf-8'

In [ ]:
start_time = time.time()  # 시작 시간 저장
df_rtn = Read_Chunk(file_path)
print("time :", time.time() - start_time) # 현재시간 - 시작시간

 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 1000000
 Processed a chunk of size: 26024
time : 32.2989068031311

In [ ]:
start_time = time.time()  # 시작 시간 저장
df_rtn = Read_pyarrow(file_path)
print("time :", time.time() - start_time) # 현재시간 - 시작시간

time : 13.139034748077393

In [ ]:
start_time = time.time()  # 시작 시간 저장
_dtype={'성별': 'object',
       '운동량': 'object',
       '탄소량': 'object'}

df_rtn = Read_dask(file_path, _dtype)
print("time :", time.time() - start_time) # 현재시간 - 시작시간

time : 0.37380552291870117

In [ ]:
df_rtn.columns

Index(['대여일자', '대여시간', '대여소번호', '대여소명', '대여구분코드', '성별', '연령대코드', '이용건수', '운동량',
       '탄소량', '이동거리', '사용시간'],
      dtype='object')

In [ ]:
df_rtn.info()

<class 'dask_expr.DataFrame'>
Columns: 12 entries, 대여일자 to 사용시간
dtypes: float64(1), int64(4), string(7)

In [ ]:
df_rtn.head()

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간
0,2020-02-01,0,1442,1442. (구)신한은행 중랑교지점,정기권,NaN,~10대,1,53.86,0.32,1360.0,6
1,2020-02-01,0,1339,1339. 삼성전자서비스 성북센터,정기권,NaN,~10대,1,10.04,0.09,390.0,3
2,2020-02-01,0,1960,1960. 화광신문사 앞,정기권,NaN,~10대,1,75.14,0.64,2750.0,24
3,2020-02-01,0,394,394. 경희궁 자이 3단지,정기권,NaN,~10대,1,28.42,0.18,780.0,3
4,2020-02-01,0,1364,1364. 성북동 치안센터 앞,정기권,NaN,~10대,1,52.97,0.41,1760.0,11

In [ ]:
df_rtn.count()

Dask Series Structure:
npartitions=1
대여구분코드    int64
탄소량         ...
Dask Name: count, 2 expressions
Expr=ReadCSV(e7d681a).count()

In [ ]:
type(df_rtn)

dask_expr._collection.DataFrame

In [ ]:
type(computed_df)

pandas.core.frame.DataFrame

---

In [ ]:
computed_df = df_rtn.compute()

In [ ]:
computed_df.columns

Index(['대여일자', '대여시간', '대여소번호', '대여소명', '대여구분코드', '성별', '연령대코드', '이용건수', '운동량',
       '탄소량', '이동거리', '사용시간'],
      dtype='object')

In [ ]:
computed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19026024 entries, 0 to 712514
Data columns (total 12 columns):
 #   Column  Dtype
---  ------  -----
 0   대여일자    object
 1   대여시간    int64
 2   대여소번호   int64
 3   대여소명    object
 4   대여구분코드  object
 5   성별      object
 6   연령대코드   object
 7   이용건수    int64
 8   운동량     object
 9   탄소량     object
 10  이동거리    float64
 11  사용시간    int64
dtypes: float64(1), int64(4), object(7)
memory usage: 1.8+ GB

In [ ]:
computed_df.head()

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간
0,2020-02-01,0,1442,1442. (구)신한은행 중랑교지점,정기권,NaN,~10대,1,53.86,0.32,1360.0,6
1,2020-02-01,0,1339,1339. 삼성전자서비스 성북센터,정기권,NaN,~10대,1,10.04,0.09,390.0,3
2,2020-02-01,0,1960,1960. 화광신문사 앞,정기권,NaN,~10대,1,75.14,0.64,2750.0,24
3,2020-02-01,0,394,394. 경희궁 자이 3단지,정기권,NaN,~10대,1,28.42,0.18,780.0,3
4,2020-02-01,0,1364,1364. 성북동 치안센터 앞,정기권,NaN,~10대,1,52.97,0.41,1760.0,11

In [ ]:
computed_df.count()

대여일자      706336
대여시간      706336
대여소번호     706336
대여소명      706336
대여구분코드    706336
성별        346011
연령대코드     706336
이용건수      706336
운동량       706336
탄소량       706336
이동거리      706336
사용시간      706336
dtype: int64

In [ ]:
df_rtn.columns

Index(['대여일자', '대여시간', '대여소번호', '대여소명', '대여구분코드', '성별', '연령대코드', '이용건수', '운동량',
       '탄소량', '이동거리', '사용시간'],
      dtype='object')

In [ ]:
type(df_rtn['성별'])

dask_expr._collection.Series

In [ ]:
df_rtn['성별'].dtype

dtype('float64')

In [ ]:
df_rtn['성별'].unique()

Dask Series Structure:
npartitions=1
    float64
        ...
Dask Name: unique, 3 expressions
Expr=Unique(frame=ReadCSV(bdf96b2)['성별'])

In [ ]:
df_rtn = df_rtn[df_rtn['성별'] == 0]

In [ ]:
df_rtn.count()

대여일자      706336
대여시간      706336
대여소번호     706336
대여소명      706336
대여구분코드    706336
성별        706336
연령대코드     706336
이용건수      706336
운동량       706336
탄소량       706336
이동거리      706336
사용시간      706336
dtype: int64

In [ ]:
df_rtn['대여일자'].head()

0    2020-01-01
1    2020-01-01
2    2020-01-01
3    2020-01-01
4    2020-01-01
Name: 대여일자, dtype: object

In [ ]:
type(df_rtn)

dask_expr._collection.DataFrame

In [ ]:
df_rtn.head()

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간
0,2020-01-01,0,1044,1044. 굽은다리역,정기권,,~10대,1,33.96,0.30,1280.0,6
1,2020-01-01,0,1656,1656. 중앙하이츠 아파트 입구,정기권,,~10대,1,40.15,0.39,1690.0,6
2,2020-01-01,0,1337,1337. 돈암성당 옆,정기권,,~10대,1,80.88,0.50,2150.0,12
3,2020-01-01,0,1984,1984. 구로구청,정기권,,~10대,1,47.36,0.43,1840.0,25
4,2020-01-01,0,2601,2601. 석촌호수 서호사거리,정기권,,~10대,1,29.34,0.26,1140.0,5