In [1]:
# 라이브러리 임포트
import os
import pandas as pd
import chardet

# 사용자 정의함수 경로 설정
import sys
sys.path.append("G:/내 드라이브/Source/_Custom_Function")
# 사용자 정의함수 불러오기

import time

import ExcelFile_Merge as em
import ExcelFile_Read as er
import ExcelFile_EDA as ee

## 대여소 정보

In [6]:
filepath = 'G:\\내 드라이브\\DataSet\\_파킷 파일\\서울시 공공자전거 대여소 정보\\'
filename = '공공자전거 대여소 정보_통합본.parquet'
start_time = time.time()
df_parquet = pd.read_parquet(filepath + filename)
print("read_parquet time :", time.time() - start_time)
df_parquet.head(5)

read_parquet time : 0.014537811279296875

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치시기,LCD,QR,운영방식,데이터등록월
20852,06173,서울자동차운전전문학원,강서구,강서구 남부순환로 216,37.546135,126.821060,2024-03-18,NaN,10.0,QR,2024-06
19007,02902,공릉풍림아파트 108동,노원구,서울특별시 노원구 섬밭로 139 공릉풍림아파트,37.628620,127.066910,2020-03-24,NaN,12.0,QR,2024-06
19015,02912,대진고등학교,노원구,서울특별시 노원구 한글비석로 97,37.638157,127.073265,2020-03-23,NaN,20.0,QR,2024-06
19014,02911,상계역중앙시장,노원구,서울특별시 노원구 한글비석로 389-2 가로판매대,37.658871,127.071915,2020-03-23,NaN,7.0,QR,2024-06
19013,02910,도깨비시장,노원구,서울특별시 노원구 동일로 1028 한의학명가,37.621864,127.074051,2020-03-25,NaN,10.0,QR,2024-06

In [8]:
filepath = 'G:\\내 드라이브\\DataSet\\_파킷 파일\\서울시 공공자전거 대여소 정보\\'
filename = '공공자전거 대여소 정보API_24.10.14.parquet'
start_time = time.time()
df_parquet = pd.read_parquet(filepath + filename)
print("read_parquet time :", time.time() - start_time)
df_parquet.head(5)

read_parquet time : 0.6775541305541992

  대여소ID  대여소번호        대여소명  거치대수         위도          경도
0  ST-4    102  망원역 1번출구 앞    15  37.555649  126.910629
1  ST-5    103  망원역 2번출구 앞    14  37.554951  126.910835
2  ST-6    104  합정역 1번출구 앞    13  37.550739  126.915085
3  ST-7    105  합정역 5번출구 앞     5  37.550007  126.914825
4  ST-8    106  합정역 7번출구 앞    12  37.548645  126.912827

### 서울시 자전거 도로

In [13]:
filepath = 'G:\\내 드라이브\\DataSet\\_최종 병합 파일\\서울시 자전거 이용시설 통계\\'
filename = '_자전거 통계_2019_2023_pivot.parquet'
start_time = time.time()
df_parquet = pd.read_parquet(filepath + filename)
print("read_parquet time :", time.time() - start_time)
df_parquet.head(5)

read_parquet time : 0.01706528663635254

,자치구,총계 연장(㎞)_2018,총계 연장(㎞)_2019,총계 연장(㎞)_2020,총계 연장(㎞)_2021,총계 연장(㎞)_2022,총계 연장(㎞)_2023,총계 노선(개)_2018,총계 노선(개)_2019,총계 노선(개)_2020,...,겸용도로(비분리형) 연장(㎞)_2020,겸용도로(비분리형) 연장(㎞)_2021,겸용도로(비분리형) 연장(㎞)_2022,겸용도로(비분리형) 연장(㎞)_2023,겸용도로(비분리형) 노선(개)_2018,겸용도로(비분리형) 노선(개)_2019,겸용도로(비분리형) 노선(개)_2020,겸용도로(비분리형) 노선(개)_2021,겸용도로(비분리형) 노선(개)_2022,겸용도로(비분리형) 노선(개)_2023
0,강남구,52.6,52.6,89.96,98.55,110.49,113.39,27,26,65,...,31.71,40.76,47.88,48.58,12,11,29,32,39,40
1,강동구,40.8,42.1,71.98,74.11,74.44,76.62,33,33,66,...,39.21,41.07,41.07,42.90,11,11,27,39,39,42
2,강북구,7.0,7.0,8.70,8.70,8.70,8.70,3,3,8,...,2.97,2.97,2.97,2.97,1,1,2,2,2,2
3,강서구,27.9,41.7,76.38,68.31,77.06,77.34,34,43,80,...,24.41,14.70,14.70,14.70,8,7,14,11,11,11
4,관악구,19.5,19.5,29.50,27.73,27.73,27.73,15,15,19,...,19.60,17.80,17.80,17.80,5,4,7,7,7,7