In [210]:
import pandas as pd
import numpy as np
import json

import folium
import folium.plugins

import time

In [212]:
# 나의 루트 경로 설정
path_dateset = 'G:/내 드라이브/DataSet/서울시 차량통행속도(월별)/2024/'

## 데이터 불러오기

### "2024년 10월 서울시 차량통행속도" 정보

In [216]:
start_time = time.time()
df_seoul_road = pd.read_parquet(path_dateset + '서울시_차량통행속도_2024.parquet')
print("read_csv time :", time.time() - start_time)

read_csv time : 1.0829074382781982

In [218]:
df_seoul_road.shape[0]

1546770

In [220]:
# 모든 컬럼을 표시하도록 설정
pd.set_option('display.max_columns', None)

In [222]:
df_seoul_road.head(2)

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,도심/외곽구분,권역구분,~01시,~02시,~03시,~04시,~05시,~06시,~07시,~08시,~09시,~10시,~11시,~12시,~13시,~14시,~15시,~16시,~17시,~18시,~19시,~20시,~21시,~22시,~23시,~24시,01시,02시,03시,04시,05시,06시,07시,08시,09시,10시,11시,12시,13시,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,20240901,일,4.19로,1080012200,아카데미하우스,국립4.19묘지,상행,1179,1,보조간선도로,외곽,강북구,46.35,41.84,48.43,57.67,44.61,37.18,42.80,44.45,35.04,36.71,40.81,39.74,35.38,27.05,31.10,28.31,29.22,32.31,28.59,35.42,28.63,51.61,44.03,51.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20240901,일,4.19로,1080012800,국립4.19묘지,국립4.19묘지입구,상행,352,1,보조간선도로,외곽,강북구,24.47,24.93,20.45,24.22,18.22,18.69,19.03,12.37,13.67,15.41,16.97,12.37,15.75,13.25,11.23,12.31,12.36,13.20,14.31,18.20,15.83,18.15,25.56,19.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [224]:
df_seoul_road['권역구분'].unique()

array(['강북구', '송파구', '양천구', '강서구', '동작구', '영등포구', '구로구', '금천구', '은평구',
       '마포구', '서대문구', '서초구', '강남구', '용산구', '관악구', '광진구', '성동구', '동대문구',
       '중랑구', '강동구', '노원구', '성북구', '중구', '종로구', '도봉구', None], dtype=object)

In [226]:
df_seoul_road.describe()

,일자,링크아이디,거리,차선수,~01시,~02시,~03시,~04시,~05시,~06시,~07시,~08시,~09시,~10시,~11시,~12시,~13시,~14시,~15시,~16시,~17시,~18시,~19시,~20시,~21시,~22시,~23시,~24시,01시,02시,03시,04시,05시,06시,07시,08시,09시,10시,11시,12시,13시,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
count,1.546770e+06,1.546770e+06,1.546770e+06,1.546770e+06,1.236564e+06,1.236487e+06,1.236367e+06,1.236270e+06,1.236127e+06,1.236501e+06,1.236535e+06,1.241007e+06,1.241140e+06,1.241070e+06,1.241402e+06,1.241281e+06,1.241192e+06,1.241583e+06,1.241411e+06,1.241439e+06,1.241453e+06,1.241545e+06,1.241590e+06,1.241599e+06,1.241611e+06,1.236784e+06,1.236600e+06,1.236593e+06,304217.000000,304193.000000,304173.000000,304108.000000,304101.000000,304117.000000,304115.000000,304135.000000,304184.000000,304183.00000,304178.000000,304160.000000,304153.000000,304199.000000,304159.000000,304157.000000,304164.000000,304202.000000,304186.000000,304193.000000,304172.00000,304221.000000,304241.000000,304250.000000
mean,2.024057e+07,1.166509e+09,5.869306e+02,2.736373e+00,3.006086e+01,3.104664e+01,3.173664e+01,3.214468e+01,3.191743e+01,3.064654e+01,2.900840e+01,2.699782e+01,2.502016e+01,2.446100e+01,2.416174e+01,2.427018e+01,2.460065e+01,2.432637e+01,2.382978e+01,2.341829e+01,2.283286e+01,2.230223e+01,2.237185e+01,2.387846e+01,2.547047e+01,2.631032e+01,2.707584e+01,2.872105e+01,30.328639,31.204163,31.889642,32.307473,32.171820,30.871942,28.925649,27.105818,25.784642,25.16246,24.739044,24.736603,24.880746,24.538921,24.100845,23.775301,23.288664,22.696886,22.392649,23.941995,25.79236,26.818679,27.628867,29.155395
std,2.875617e+02,2.804160e+08,4.650733e+02,1.224611e+00,1.503536e+01,1.526358e+01,1.528632e+01,1.520826e+01,1.499933e+01,1.434292e+01,1.320540e+01,1.265045e+01,1.254671e+01,1.220424e+01,1.188530e+01,1.206527e+01,1.240641e+01,1.224529e+01,1.199172e+01,1.174868e+01,1.137901e+01,1.123050e+01,1.179387e+01,1.226739e+01,1.259780e+01,1.287872e+01,1.347925e+01,1.448888e+01,14.986719,15.154868,15.187546,15.181964,15.070463,14.542573,13.162038,12.538501,12.669705,12.54127,12.263254,12.378089,12.598449,12.401777,12.217619,12.037563,11.640876,11.365307,11.644826,12.175015,12.73916,13.172949,13.781598,14.567655
min,2.024010e+07,1.000000e+09,7.000000e+00,1.000000e+00,2.720000e+00,2.050000e+00,2.170000e+00,2.000000e+00,1.920000e+00,3.600000e+00,1.900000e+00,1.500000e+00,1.080000e+00,1.170000e+00,1.080000e+00,1.170000e+00,1.580000e+00,1.330000e+00,1.170000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.080000e+00,1.000000e+00,1.830000e+00,1.770000e+00,2.210000e+00,3.190000,2.080000,2.120000,1.500000,2.170000,3.880000,3.490000,1.420000,2.580000,2.53000,2.250000,1.250000,1.250000,1.080000,1.500000,1.580000,1.250000,1.500000,1.000000,1.170000,2.12000,2.270000,2.720000,3.880000
25%,2.024032e+07,1.060014e+09,3.110000e+02,2.000000e+00,2.177000e+01,2.263000e+01,2.322000e+01,2.351000e+01,2.330000e+01,2.224000e+01,2.115000e+01,1.955000e+01,1.748000e+01,1.713000e+01,1.705000e+01,1.707000e+01,1.719000e+01,1.700000e+01,1.665000e+01,1.637000e+01,1.598000e+01,1.556000e+01,1.537000e+01,1.660000e+01,1.798000e+01,1.875000e+01,1.930000e+01,2.052000e+01,22.000000,22.760000,23.270000,23.500000,23.330000,22.180000,20.890000,19.640000,18.190000,17.64000,17.400000,17.380000,17.360000,17.120000,16.780000,16.560000,16.280000,15.910000,15.470000,16.700000,18.22000,19.060000,19.660000,20.870000
50%,2.024060e+07,1.140006e+09,4.790000e+02,3.000000e+00,2.621000e+01,2.715000e+01,2.786000e+01,2.837000e+01,2.825000e+01,2.729000e+01,2.612000e+01,2.431000e+01,2.252000e+01,2.194000e+01,2.165000e+01,2.161000e+01,2.173000e+01,2.151000e+01,2.111000e+01,2.083000e+01,2.045000e+01,2.007000e+01,2.000000e+01,2.118000e+01,2.252000e+01,2.324000e+01,2.381000e+01,2.508000e+01,26.510000,27.390000,28.100000,28.570000,28.520000,27.470000,26.020000,24.400000,23.130000,22.48000,22.060000,21.980000,21.940000,21.670000,21.320000,21.090000,20.800000,20.380000,20.010000,21.260000,22.79000,23.650000,24.250000,25.500000
75%,2.024082e+07,1.210004e+09,7.060000e+02,3.000000e+00,3.224000e+01,3.339000e+01,3.438000e+01,3.514000e+01,3.503000e+01,3.384000e+01,3.241000e+01,3.031000e+01,2.859000e+01,2.786000e+01,2.737000e+01,2.742000e+01,2.772000e+01,2.743000e+01,2.702000e+01,2.672000e+01,2.627000e+01,2.582000e+01,2.591000e+01,2.718000e+01,2.848000e+01,2.912000e+01,2.966000e+01,3.113000e+01,32.670000,33.770000,34.810000,35.600000,35.610000,34.330000,32.540000,30.470000,29.230000,28.50000,27.920000,27.860000,27.990000,27.660000,27.300000,27.070000,26.720000,26.170000,25.920000,27.290000,28.88000,29.700000,30.280000,31.680000
max,2.024103e+07,3.201511e+09,5.328000e+03,1.100000e+01,1.152500e+02,1.144200e+02,1.188900e+02,1.123300e+02,1.177500e+02,1.097500e+02,1.082500e+02,1.075800e+02,1.031500e+02,1.021600e+02,1.003100e+02,1.001700e+02,1.152000e+02,1.033300e+02,1.002500e+02,1.020800e+02,1.006700e+02,9.958000e+01,9.983000e+01,1.041700e+02,1.015800e+02,1.141700e+02,1.096700e+02,1.130000e+02,111.750000,113.250000,112.830000,112.750000,112.330000,108.330000,106.170000,104.170000,104.750000,101.42000,98.420000,97.420000,96.580000,95.830000,96.250000,96.520000,96.920000,96.330000,97.670000,98.250000,99.08000,102.920000,106.830000,109.670000

In [227]:
df_seoul_road.columns

Index(['일자', '요일', '도로명', '링크아이디', '시점명', '종점명', '방향', '거리', '차선수', '기능유형구분',
       '도심/외곽구분', '권역구분', '~01시', '~02시', '~03시', '~04시', '~05시', '~06시',
       '~07시', '~08시', '~09시', '~10시', '~11시', '~12시', '~13시', '~14시', '~15시',
       '~16시', '~17시', '~18시', '~19시', '~20시', '~21시', '~22시', '~23시', '~24시',
       '01시', '02시', '03시', '04시', '05시', '06시', '07시', '08시', '09시', '10시',
       '11시', '12시', '13시', '14시', '15시', '16시', '17시', '18시', '19시', '20시',
       '21시', '22시', '23시', '24시'],
      dtype='object')

---
### 출근_시, 퇴근_시 컬럼 추가

In [229]:
df_seoul_road['출근_시'] = df_seoul_road['~08시'] + df_seoul_road['~09시']    # 출근(07 ~ 09)
df_seoul_road['퇴근_시'] = df_seoul_road['~18시'] + df_seoul_road['~19시']    # 퇴근(17 ~ 19)

In [230]:
_columns = ['일자', '요일', '권역구분', '출근_시', '퇴근_시']
df_seoul_road_2 = df_seoul_road[_columns]

In [235]:
df_seoul_road_2.head(2)

         일자 요일 권역구분   출근_시   퇴근_시
0  20240901  일  강북구  79.49  60.90
1  20240901  일  강북구  26.04  27.51

---
### 평일(월 ~ 금) 데이터만 가져오기

In [238]:
df_seoul_road_3 = df_seoul_road_2[df_seoul_road_2['요일'].isin(['월', '화', '수', '목', '금'])]

In [240]:
print(f'df_seoul_road_2.shape[0] : {df_seoul_road_2.shape[0]}')
print(f'df_seoul_road_3.shape[0] : {df_seoul_road_3.shape[0]}')

df_seoul_road_2.shape[0] : 1546770
df_seoul_road_3.shape[0] : 1110641

In [242]:
df_seoul_road_3.head(2)

            일자 요일 권역구분   출근_시   퇴근_시
5071  20240902  월  강북구  76.71  59.09
5072  20240902  월  강북구  28.11  24.68

In [244]:
df_seoul_road_4 = df_seoul_road_3.groupby(['권역구분']).agg({'출근_시': 'mean', '퇴근_시': 'mean'}).reset_index()

In [246]:
df_seoul_road_4.shape[0]

25

In [248]:
df_seoul_road_4.value_counts()

권역구분  출근_시       퇴근_시
강남구   51.579545  40.105382    1
서대문구  46.218364  42.574795    1
중구    44.989547  35.693627    1
종로구   45.916842  38.504096    1
은평구   42.928557  39.130044    1
용산구   56.677049  45.861512    1
영등포구  49.503831  43.172946    1
양천구   54.870645  48.352028    1
송파구   49.121225  44.604786    1
성북구   49.193666  42.880351    1
성동구   53.191679  46.294441    1
서초구   56.119908  46.206953    1
마포구   52.018296  45.387336    1
강동구   45.185412  42.059979    1
동작구   49.036504  44.319693    1
동대문구  45.797787  41.894950    1
도봉구   44.694802  40.767734    1
노원구   46.984113  42.368538    1
금천구   50.562327  43.005625    1
구로구   49.328719  44.744203    1
광진구   54.329728  47.536016    1
관악구   54.350212  49.353611    1
강서구   46.509337  42.143603    1
강북구   42.282277  37.819982    1
중랑구   46.349654  40.648392    1
Name: count, dtype: int64

In [250]:
df_seoul_road_4.head()

  권역구분       출근_시       퇴근_시
0  강남구  51.579545  40.105382
1  강동구  45.185412  42.059979
2  강북구  42.282277  37.819982
3  강서구  46.509337  42.143603
4  관악구  54.350212  49.353611

In [252]:
# have_bikes = rental.groupby('자치구').size()
df_seoul_road_출근 = df_seoul_road_4.groupby('권역구분')['출근_시'].mean()
df_seoul_road_퇴근 = df_seoul_road_4.groupby('권역구분')['퇴근_시'].mean()

---
### 지도에 자치구 이름 표시관련 - 위도/경도 정리

In [255]:
dic_gus = {
    '송파구': [37.5046, 127.1187],
    '강서구': [37.5642, 126.8255],
    '강남구': [37.4915, 127.0624],
    '영등포구': [37.5244, 126.9031],
    '노원구': [37.6518, 127.0737],
    '서초구': [37.4841, 127.0126],
    '마포구': [37.5568, 126.9082],
    '강동구': [37.5527, 127.1448],
    '구로구': [37.4967, 126.8454],
    '양천구': [37.5214, 126.8595],
    '종로구': [37.5949, 126.9676],
    '중랑구': [37.5971, 127.0912],
    '은평구': [37.6205, 126.9257],
    '중구': [37.5601, 126.9985],
    '성동구': [37.5511, 127.0366],
    '동대문구': [37.5840, 127.0514],
    '용산구': [37.5348, 126.9793],
    '광진구': [37.5484, 127.0854],
    '서대문구': [37.5810, 126.9378],
    '성북구': [37.6044, 127.0147],
    '관악구': [37.4689, 126.9470],
    '도봉구': [37.6716, 127.0322],
    '금천구': [37.4640, 126.9020],
    '동작구': [37.5048, 126.9508],
    '강북구': [37.6382, 127.0116]
}

In [263]:
save_name = '(folium)서울시_도로혼잡률'

# 지도 생성
# center = [37.541, 126.986]
center = [37.5665, 126.9780]

# bike_map = folium.Map(location=center, zoom_start=13, tiles='openstreetmap', name='OpenStreetMap')
bike_map = folium.plugins.DualMap(location=center, tiles="openstreetmap", name='OpenStreetMap', zoom_start=11)

# 자치구 구분 표
geo_str2 = json.load(open('G:\\내 드라이브\\DataSet\\seoul_municipalities_geo_simple.json', encoding='utf-8'))

fg0_1 = folium.FeatureGroup(name="출근", show=True).add_to(bike_map.m1)
choropleth = folium.Choropleth(geo_data = geo_str2,
                  data = df_seoul_road_출근,
                  name = '출근',
                  key_on = 'feature.properties.SIG_KOR_NM',
                  fill_color = 'Reds',
                  fill_opacity=0.7              # 채우기 불투명도
                )
choropleth.geojson.add_to(fg0_1)
# 각 구의 중심에, 자치구별 합계 표시
for idx, val in zip(df_seoul_road_출근.index, df_seoul_road_출근.values):
    folium.Marker(
        location=[dic_gus[idx][0] + 0.0055, dic_gus[idx][1]],
        popup=round(val, 2),
        icon=folium.DivIcon(html=f"<div style='font-size: 7pt; color: black; font-family: Arial; font-weight: bold;'>{round(val, 2)}</div>")
    ).add_to(fg0_1)
# =================================================================


fg0_2 = folium.FeatureGroup(name="퇴근", show=True).add_to(bike_map.m2)
choropleth = folium.Choropleth(geo_data = geo_str2,
                  data = df_seoul_road_퇴근,
                  name = '퇴근',
                  key_on = 'feature.properties.SIG_KOR_NM',
                  fill_color = 'Reds',
                  fill_opacity=0.7              # 채우기 불투명도
                )
choropleth.geojson.add_to(fg0_2)
# 각 구의 중심에, 자치구별 합계 표시
for idx, val in zip(df_seoul_road_퇴근.index, df_seoul_road_퇴근.values):
    folium.Marker(
        location=[dic_gus[idx][0] + 0.0055, dic_gus[idx][1]],
        popup=round(val, 2),
        icon=folium.DivIcon(html=f"<div style='font-size: 7pt; color: black; font-family: Arial; font-weight: bold;'>{round(val, 2)}</div>")
    ).add_to(fg0_2)
# =================================================================

# =================================================================

# FeatureGroup 생성
fg_both = folium.FeatureGroup(name="markers_both").add_to(bike_map)

# 각 구의 중심에 구 이름 표시
#fg1 = folium.FeatureGroup(name="구_이름", show=True).add_to(bike_map)
for _gu, _location in dic_gus.items():
    folium.Marker(
        location=_location,
        popup=_gu,
        name = '구_이름',
        icon=folium.DivIcon(html=f"<div style='font-size: 7pt; color: black; font-family: Arial; font-weight: bold;'>{_gu}</div>")
    ).add_to(fg_both)


# 지도 클릭 시, 좌표(위도,경로) 팝업으로 표시
folium.LatLngPopup().add_to(bike_map.m1)
folium.LatLngPopup().add_to(bike_map.m2)

#folium.TileLayer('openstreetmap', name='OpenStreetMap').add_to(bike_map)
folium.TileLayer('cartodbpositron', name='CartoDB Positron').add_to(bike_map.m1)
folium.TileLayer('cartodbdark_matter', name='CartoDB Dark Matter').add_to(bike_map.m1)
folium.TileLayer('cartodbpositron', name='CartoDB Positron').add_to(bike_map.m2)
folium.TileLayer('cartodbdark_matter', name='CartoDB Dark Matter').add_to(bike_map.m2)

folium.LayerControl().add_to(bike_map.m1)
folium.LayerControl().add_to(bike_map.m2)

# jupyter 에서 곧장 지도 표시하기
#bike_map

# web에서 표시하기
# 지도 저장
bike_map.save(save_name + ".html")
import webbrowser
webbrowser.open(save_name + ".html")

True